### ISSUE TITLE
공통 - TagFilter 컴포넌트 스타일링 리펙토링 

### ISSUE THREAD

**Issue by pkb9239** [Team-kiwing/Team-3seco-kiwing-fe#94]
# 📌간단한 기능 설명
공통 컴포넌트인 TagFilter의 스타일을 리펙토링합니다.
# 📄Todo
- [x] `useResize` 사용하여 모바일에 따라 뱃지크기 변경 
- [x]  전체적인 스타일링 변경
<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0

**Comment by SoJuSo** [comment]
경빈님의 코딩열차는 멈추지 않는다..
사실 진정한 불도저는 경빈님이 아니였을까요..?
